### ISSUE TITLE
Nothing happens when we click on links at top of header section

### ISSUE THREAD

**Issue by NishantNaikwade** [shubhangidhole1210/RetailApplication#5]
Actual : 
When we click on hyperlink like Assured, Advertise, Gift Card etc page is not redirected to anywhere.

Actual : 
When we click on hyperlink like Assured, Advertise, Gift Card etc UI should be redirected to respective pages.

**Comment by shubhangidhole1210** [comment]
I have created assured.html, giftCard.html, customerCare.html, and downlodApp.html pages.
have completed assured.html page and downlodApp.htmll page UI
CustomerCare.html and giftCard UI remaining

**Comment by NishantNaikwade** [comment]
Redirection is implemented for links on links in top of header.
